name: Node.js Continuous Integration

# Will run on both push and pull rquest to main branch
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # Run all CI jobs on version 14, 16 og 18 of Node.js

    steps:
      - uses: actions/checkout@v3
      - name: Bruk Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -g npm # To make sure npm command works on next commands
      - run: npm ci # Install all dependencies from package-lock.json
      - run: npm test # Run the command specified in npm test: 'mocha ./test/' which will run all tests