name: Node.js Continuous Integration

# Vil kjøre både ved push til main branch eller pull request til main branch.
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # Kjører alle CI jobber under på versjon 14, 16 og 18 av Node.js

    steps:
      - uses: actions/checkout@v3
      - name: Bruk Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -g npm # For å sikre at videre kommandoer fungerer
      - run: npm ci # Installerer alle dependencies fra package-lock.json
      - run: npm test # Kjører kommandoen spesifisert i npm test: 'mocha ./test/'